apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority-apps
value: 10000
description: "Low priority workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-apps
value: 1000000
preemptionPolicy: PreemptLowerPriority
